### ISSUE TITLE
Unhandled Runtime Error Error:   Call Stack o._fetch async H.create

### ISSUE THREAD

**Issue by medraud94private** [a16z-infra/ai-town#105]
We've encountered a runtime issue with our web application which seems to be related to the @clerk/clerk-js library.

Error encountered: Unhandled Runtime Error
Relevant functions: o._fetch and H.create
Error location: https://suited-cicada-78.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js
While the precise root cause is not immediately clear, it appears there might be issues in the data retrieval process within the o._fetch function or during data creation in H.create.

Could you please investigate further? Additionally, it might be helpful to consult the library's documentation or community for potential solutions.
![스크린샷 2023-08-17 오후 4 00 00](https://github.com/a16z-infra/ai-town/assets/127918473/b0bcbd62-390f-440e-adbe-290f8eb96562)

**Comment by Michael-A-Costa** [comment]
I have the same issue. Here is my console output if that helps.
```
PS C:\Users\pokes\ai-town> npm run dev

> ai-town@0.0.0 dev
> npm-run-all dev:init --parallel dev:frontend dev:backend


> ai-town@0.0.0 dev:init
> convex dev --run init --until-success

✔ 12:29:00 Convex functions ready! (3.58s)
✔ Finished running function "init"
'*************'

> ai-town@0.0.0 dev:frontend
> next dev


> ai-town@0.0.0 dev:backend
> convex dev

- info Loaded env from C:\Users\pokes\ai-town\.env.local
- warn You have enabled experimental feature (serverActions) in next.config.js.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

- ready started server on [::]:3000, url: http://localhost:3000
⠙ Preparing Convex functions...
⠼ Preparing Convex functions...
⠴ Checking for index or schema changes...
⠇ Backfilling indexes and checking that documents match your schema...
⠙ Backfilling indexes and checking that documents match your schema...
- info Loaded env from C:\Users\pokes\ai-town\.env.local
⠸ Backfilling indexes and checking that documents match your schema...
⠧ Backfilling indexes and checking that documents match your schema...
✔ 12:29:05 Convex functions ready! (3.58s)
- event compiled client and server successfully in 1493 ms (2242 modules)
- wait compiling...
- event compiled successfully in 215 ms (902 modules)
- error node_modules\@pixi\sound\lib\utils\supported.mjs (27:0) @ validateFormats
- error ReferenceError: document is not defined
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at eval (./src/components/MusicButton.tsx:11:69)
    at (ssr)/./src/components/MusicButton.tsx (C:\Users\pokes\ai-town\.next\server\app\page.js:6304:1)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
null
- wait compiling /favicon.ico/route (client and server)...
- event compiled client and server successfully in 227 ms (2270 modules)
- error node_modules\@pixi\sound\lib\utils\supported.mjs (27:0) @ validateFormats
- error ReferenceError: document is not defined
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
    at eval (./src/components/MusicButton.tsx:11:69)
    at (ssr)/./src/components/MusicButton.tsx (C:\Users\pokes\ai-town\.next\server\app\page.js:6304:1)
    at __webpack_require__ (C:\Users\pokes\ai-town\.next\server\webpack-runtime.js:33:43)
null
```

**Comment by Kevin-free** [comment]
@medraud94private @Michael-A-Costa 
I also encounter this problem, do you know how to solve it?

I followed the tutorial "create a new Convex Template" and "Copy the JWKS endpoint URL" in Clerk.

The environment variable `CLERK_ISSUER_URL=https://communal-moth-26.clerk.accounts.dev/.well-known/jwks.json` has been set in convex

`.env.local` has:
```
CLERK_ISSUER_URL=https://communal-moth-26.clerk.accounts.dev/.well-known/jwks.json
```

```shell
> npm run dev

> ai-town@0.0.0 dev
> npm-run-all dev:init --parallel dev:frontend dev:backend

> ai-town@0.0.0 dev:init
> convex dev --run init --until-success

✔ 12:12:34 Convex functions ready! (10.64s)
✔ Finished running function "init"
'4ccewghnza6p57s589tvrhgd9j4ee0r'

> ai-town@0.0.0 dev:backend
> convex dev

> ai-town@0.0.0 dev:frontend
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /Users/***/1619-ai-town/.env.local
- warn You have enabled experimental feature (serverActions) in next.config.js.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

⠴Preparing Convex functions...
⠇ Preparing Convex functions...  
⠙ Preparing Convex functions...
✔ 12:12:46 Convex functions ready! (7.15s)
- wait compiling /src/middleware (client and server)...
- event compiled successfully in 218 ms (244 modules)
- wait compiling /page (client and server)...
- event compiled client and server successfully in 2.4s (2411 modules)
- wait compiling...
- event compiled successfully in 132 ms (999 modules)
```

Running error:

```
Unhandled Runtime Error
Error:

Call Stack
o._fetch
https://communal-moth-26.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js (2:77243)
async H. create
https://communal-moth-26.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js (2:107743)
```

<img width="1440" alt="image" src="https://github.com/a16z-infra/ai-town/assets/26422757/1efb5b55-76b7-4ad0-9a3e-ad25e7103f2b">

<img width="1440" alt="image" src="https://github.com/a16z-infra/ai-town/assets/26422757/321b1c51-2b8c-4991-b803-cb3e99e51109">

<img width="1440" alt="image" src="https://github.com/a16z-infra/ai-town/assets/26422757/2746f99b-e032-4fd1-9b04-6529f9a73e87">

**Comment by Kevin-free** [comment]
When I update the project, and update `npm`, I get another error 🥹

```shell
Unhandled Runtime Error
**Error: Clerk: auth() was called but it looks like you aren't using `authMiddleware` in your middleware file.** Please use `authMiddleware` and make sure your middleware matcher is configured correctly and it matches this route or page. See https https://clerk.com/docs/quickstarts/get-started-with-nextjs
```

```shell
> npm version
{
   'ai-town': '0.0.0',
   npm: '9.8.1',
   node: '18.0.0',
   v8: '10.1.124.8-node.13',
   uv: '1.43.0',
   zlib: '1.2.11',
   brotli: '1.0.9',
   ares: '1.18.1',
   modules: '108',
   nghttp2: '1.47.0',
   napi: '8',
   llhttp: '6.0.4',
   openssl: '3.0.2+quic',
   cldr: '41.0',
   icu: '71.1',
   tz: '2022a',
   unicode: '14.0',
   ngtcp2: '0.1.0-DEV',
   nghttp3: '0.1.0-DEV'
}
```

<img width="1440" alt="image" src="https://github.com/a16z-infra/ai-town/assets/26422757/4bb6eb03-d298-4416-9664-d1afd4e2cb26">

**Comment by Kevin-free** [comment]
> @medraud94private @Michael-A-Costa I also encounter this problem, do you know how to solve it?
> 
> I followed the tutorial "create a new Convex Template" and "Copy the JWKS endpoint URL" in Clerk.
> 
> The environment variable `CLERK_ISSUER_URL=https://communal-moth-26.clerk.accounts.dev/.well-known/jwks.json` has been set in convex
> 
> `.env.local` has:
> 
> ```
> CLERK_ISSUER_URL=https://communal-moth-26.clerk.accounts.dev/.well-known/jwks.json
> ```
> 
> ```shell
> > npm run dev
> 
> > ai-town@0.0.0 dev
> > npm-run-all dev:init --parallel dev:frontend dev:backend
> 
> > ai-town@0.0.0 dev:init
> > convex dev --run init --until-success
> 
> ✔ 12:12:34 Convex functions ready! (10.64s)
> ✔ Finished running function "init"
> '4ccewghnza6p57s589tvrhgd9j4ee0r'
> 
> > ai-town@0.0.0 dev:backend
> > convex dev
> 
> > ai-town@0.0.0 dev:frontend
> > next dev
> 
> - ready started server on 0.0.0.0:3000, url: http://localhost:3000
> - info Loaded env from /Users/***/1619-ai-town/.env.local
> - warn You have enabled experimental feature (serverActions) in next.config.js.
> - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 
> ⠴Preparing Convex functions...
> ⠇ Preparing Convex functions...  
> ⠙ Preparing Convex functions...
> ✔ 12:12:46 Convex functions ready! (7.15s)
> - wait compiling /src/middleware (client and server)...
> - event compiled successfully in 218 ms (244 modules)
> - wait compiling /page (client and server)...
> - event compiled client and server successfully in 2.4s (2411 modules)
> - wait compiling...
> - event compiled successfully in 132 ms (999 modules)
> ```
> 
> Running error:
> 
> ```
> Unhandled Runtime Error
> Error:
> 
> Call Stack
> o._fetch
> https://communal-moth-26.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js (2:77243)
> async H. create
> https://communal-moth-26.clerk.accounts.dev/npm/@clerk/clerk-js@4/dist/clerk.browser.js (2:107743)
> ```
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/26422757/262861162-1efb5b55-76b7-4ad0-9a3e-ad25e7103f2b.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/26422757/262860289-321b1c51-2b8c-4991-b803-cb3e99e51109.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/26422757/262858573-2746f99b-e032-4fd1-9b04-6529f9a73e87.png">

I know how to solve it, the `name` of JWT Templates in clerk should be consistent with the `Application ID` in convex (I don’t know how to modify `Application ID` in convex, and why the default is `convex`)

![image](https://github.com/a16z-infra/ai-town/assets/26422757/1dd34354-06aa-4040-91ac-85473752190f)

![image](https://github.com/a16z-infra/ai-town/assets/26422757/da301b71-0779-4162-8c0a-33d87a83dbe7)

<img width="1440" alt="image" src="https://github.com/a16z-infra/ai-town/assets/26422757/c2f512fa-b25f-49e7-8e49-de0b40f12eed">

**Comment by arfazhxss** [comment]
@jamwt @bcjordan the issue seems to have been resolved. I have encountered this exact issue and have fixed it through this thread. I think this issue can be closed.

**Comment by mahfuj80** [comment]
I also face this issue when I try to clone and run an old repository.
![Uploading Screenshot_9.png…]()
