### ISSUE TITLE
Pop OS - Agents Not Having Conversations

### ISSUE THREAD

**Issue by AstralHazz** [a16z-infra/ai-town#231]
I keep getting these errors when I run AI Town

--

2024-05-08T00:54:45.082187Z ERROR common::errors: Not reporting above error: Sentry is not configured

--

Documents read from or written to the table "Inputs" changed while this mutation was being run and on every subsequent retry.

--

5/7/2024, 7:55:29 PM \[CONVEX A(aiTown/agentOperations:agentGenerateMessage)\] Uncaught TypeError: fetch failed

at async <anonymous> (../../convex/util/llm.ts:91:14)

at async retryWithBackoff (../../convex/util/llm.ts:248:22)

at async chatCompletion (../../convex/util/llm.ts:90:4)

at async startConversationMessage (../../convex/agent/conversation.ts:57:14)

at async handler (../../convex/aiTown/agentOperations.ts:74:6)

--

any help or insight would be greatly appreciated! I'm a total noob when it comes to this stuff and I really want to try AI Town! I want to be able to customize the agents in the game. The errors keep even the default agents from conversing properly (or really at all).

**Comment by AstralHazz** [comment]
I tried to run it again just now and now my computer won't boot now... I'm currently trying to install a different distro (Mint Cinnamon). I'll get back to you as soon as I can if AI Town fails again
