### ISSUE TITLE
vector dimensions issue

### ISSUE THREAD

**Issue by uannyao** [a16z-infra/ai-town#255]
I have tried the meta-llama/Llama-3-8b-chat-hf chatmodel and togethercomputer/m2-bert-80M-8k-retrieval embedding model with embeddingDimension: 768, but I'm having the following error many times when agents are having conversations:

9/30/2024, 5:59:09 PM [CONVEX A(aiTown/agentOperations:agentGenerateMessage)] Uncaught Error: Expected a vector with dimensions 768, received 1024.
    at async searchMemories (../../convex/agent/memory.ts:164:12)
    at async startConversationMessage (../../convex/agent/conversation.ts:34:4)
    at async handler (../../convex/aiTown/agentOperations.ts:74:6)

**Comment by ianmacartney** [comment]
You might want to clear the `embeddingsCache` table - this command will do
it:
`npx convex import --table embeddingsCache --replace --format jsonLines
/dev/null -y`
Or drop console logs along the code path to figure out where the larger
embedding is coming from
